#!/bin/bash
current_time=$(date "+%Y.%m.%d-%H.%M.%S") 
$1  += $current_time

git add . ;
git commit -m  '$1';
git push origin master;
echo "*****"
echo "$1"
# echo "${message}"
echo "*****"

eb deploy resume-env --profile eb-cli2 ;
