#!/bin/bash
current_time=$(date "+%Y.%m.%d-%H.%M.%S")

git add . ;
git commit -m '$current_time' ;
git push origin master;
echo "*****"
echo "Depoloying to AWS EB"
echo "*****"

eb deploy resume-env --profile eb-cli2 ;
